#!/bin/sh
# Debian ZMap Install

sudo apt-get install build-essential cmake libgmp3-dev gengetopt libpcap-dev flex byacc libjson-c-dev pkg-config libunistring-dev
sudo apt-get install zmap

cmake -DENABLE_HARDENING=ON